blank_issues_enabled: false
contact_links:
  - name: Docs 📘
    url: https://github.com/orbe-soft/orbe-root/blob/main/docs/issue-template-docs.md
    about: See the documentation to understand how to use each template.
